name: Go
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: articulate/actions-markdownlint@v1
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.x"
      - name: Install dependencies
        run: go mod download
      - name: Install protoc-gen-go
        run: go install github.com/golang/protobuf/protoc-gen-go@latest
      - name: Install protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Go generate
        run: go generate ./...
      - name: Test with the Go CLI
        run: go test ./...
      - name: Build
        run: go build -v ./...
